export const ENGINEERING_FACTS = [
  "Pipe stress analysis exists so the plant is still standing after the first thermal cycle.",
  "A good piping engineer routes for the fitter who has to build it, not just the model that renders it.",
  "ASME B31.3 governs process piping; B31.1 governs power piping — mixing them up is a classic junior mistake.",
  "The shortest route is rarely the right route once you account for support spacing and flexibility.",
  "Schedule number in a pipe spec refers to wall thickness, not a delivery timeline.",
  "Every elbow you remove from a line is a support you don't have to design.",
  "Slug flow in two-phase lines is why supports near knock-out drums are over-designed on purpose.",
  "Isometrics lie less than 3D models when it comes to field fit-up — always cross-check both.",
  "Dead legs in piping systems are breeding grounds for corrosion and microbiological growth.",
  "The 3D rule: for every 3 pipe diameters of straight run, you need one diameter of flexibility.",
  "Spring hangers should never be adjusted from their cold position to hot — install them at the cold load.",
  "A pipe stress analysis is only as good as the boundary conditions you give it.",
  "Flange leakage checks are often forgotten but are the most common source of field rework.",
  "Thermal growth of piping must be calculated relative to the equipment nozzle, not the ground.",
  "Pipe supports near equipment nozzles should be placed within 3–5 pipe diameters to protect the nozzle.",
  "Two-phase flow requires larger pipe sizing than single-phase to avoid slug formation.",
  "Expansion loops are cheaper than expansion joints and require zero maintenance.",
  "Pressure relief valve discharge piping must be designed for reaction forces, not just flow.",
  "Pipe specification changes at class boundaries are one of the most common sources of NCRs.",
  "A piping isometric is a legal document in many jurisdictions — accuracy matters.",
  "Insulation thickness affects pipe routing clearances more than most designers realize.",
  "Pipe routing through pipe racks follows a hierarchy: hot lines on top, cold lines below, gravity lines sloped.",
  "The cold pull is a physical correction — never skip it during construction.",
  "Hydrotest pressure is always higher than design pressure — the pipe wall must account for this.",
  "Stress intensification factors (SIFs) at branch connections can be 2–3× the nominal stress.",
  "Pipe flexibility analysis must consider the worst thermal case, not the average operating condition.",
  "A piping designer who visits the field becomes twice as good within a month.",
  "The most expensive pipe route is the one that requires field rework.",
  "Piping and structural steel share the same rack — coordination is not optional.",
  "Dead legs longer than 3 diameters should be avoided in process piping.",
  "Pipe vibration is usually a flow-induced problem, not a structural one.",
  "The correct way to handle thermal movement at equipment is with proper flexibility, not by forcing the nozzle.",
  "Piping codes exist because plants failed without them — respect the code.",
  "A good P&ID is the single most important document in a piping project.",
  "Pipe wall thickness calculations must account for corrosion allowance, erosion, and mill tolerance.",
  "Pig launchers and receivers require specific straight pipe lengths upstream and downstream.",
  "Pipe stress is cumulative — thermal, pressure, weight, and seismic all combine.",
  "The allowable span table is your friend — never guess pipe support spacing.",
  "Low-point drains and high-point vents are small details that prevent big problems.",
  "Pipe color coding follows ASME A13.1 — it's not decorative, it's safety.",
  "The number one cause of piping failure is corrosion, not overpressure.",
  "A bellows expansion joint has a finite life — count the cycles.",
  "Pipe supports must allow thermal movement in the correct direction — constraining it causes failure.",
  "The piping design review is where 80% of field problems are prevented.",
  "Chemical injection piping requires special materials because the chemicals are often more corrosive than the process.",
  "Pipe routing in a hazardous area must consider vapor density — heavier-than-air fluids settle in trenches.",
  "Instrument connections on piping are not afterthoughts — they need proper takeoff locations and protection.",
  "The minimum bending radius for pipe bending is typically 5D — tighter and you risk buckling.",
  "Double block and bleed valve arrangements are safety-critical — design them correctly.",
  "Pipe specification is the DNA of a piping project — get it wrong and everything downstream fails.",
  "Elevation changes in pipe racks require careful coordination with structural steel.",
  "Thermal sleeve nozzles protect equipment from thermal shock — don't skip them.",
  "Pipe fatigue failure occurs at stress levels well below the yield strength — cyclic loading is deceptive.",
  "The piping material class document defines every pipe, fitting, and flange in the system.",
  "Pipe routing for cryogenic services requires special considerations for contraction and embrittlement.",
  "Vibration analysis should be part of every piping design, not an afterthought.",
  "The biggest enemy of a good piping design is compressed schedule and changed scope.",
  "Pipe support type selection: rigid for weight, variable spring for thermal, constant spring for large movements.",
  "Pipe specifications must account for the operating envelope — startup, shutdown, and upset conditions.",
  "Safety showers and eyewash stations must be within 10 seconds of walking distance in hazardous areas.",
  "Pipe welding procedures must match the material — CWI verification is not optional.",
  "The minimum wall thickness is always greater than what the pressure alone requires.",
  "Pipe routing must maintain minimum clearance from electrical equipment — arc flash zones are real.",
  "Flexible metal hoses are not substitutes for proper pipe flexibility analysis.",
  "A piping designer should never put a valve where nobody can reach it.",
  "Pipe stress analysis considers both sustained (weight + pressure) and occasional (wind, seismic) loads.",
  "Pipe support locations must be calculated, not placed by convenience.",
  "The pipe class index is your quickest reference for what's allowed in a given service.",
  "Design for maintenance access — a valve hidden behind 50 pipes will never be maintained properly.",
  "Pipe air vents are essential at high points in liquid-filled systems to prevent vapor lock.",
  "The isometric drawing is the pipe fitter's bible — it must be complete, accurate, and clear.",
  "Dead weight loads on long pipe spans can cause permanent sagging if supports are inadequate.",
  "Pipe specification overrides must be reviewed by the lead engineer — no exceptions.",
  "A piping designer who documents their routing decisions saves the next person weeks of rework.",
  "Pipe support near a control valve should not restrict the valve's thermal movement.",
  "FPSO piping design adds ship motion considerations that fixed-platform designers never face.",
  "Pipe stress analysis software is a tool, not a replacement for engineering judgment.",
  "Pipe class boundaries are where most leaks originate — double-check every transition.",
  "Cryogenic pipe supports must account for thermal contraction and prevent cold spots.",
  "The best piping designs are the ones that the construction crew never complain about.",
  "Pipe routing through seismic zones requires special attention to flexibility and restraint.",
  "Material traceability for pressure piping is a code requirement, not a suggestion.",
  "Pipe support welding procedures must match the pipe material — mixing specs is dangerous.",
  "The most overlooked piping detail is the drain and vent location — until startup.",
  "Pipe flexibility is cheapest to add in the 3D model and most expensive to add in the field.",
];

export function getRandomFact(): string {
  return ENGINEERING_FACTS[Math.floor(Math.random() * ENGINEERING_FACTS.length)];
}

export function getFactForDate(dateStr: string): string {
  // Deterministic fact selection based on date
  const hash = dateStr.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  return ENGINEERING_FACTS[hash % ENGINEERING_FACTS.length];
}
